import type { Metadata } from "next";
import { Lora, Roboto } from "next/font/google";
import "./globals.css";
import { GlobalErrorProvider } from "@/context/global-error-context";

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora", 
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${lora.variable} ${roboto.variable} antialiased`} suppressHydrationWarning={true}>
        <GlobalErrorProvider>{children}</GlobalErrorProvider>
      </body>
    </html>
  );
}
