import type { Metadata } from "next";
import { Lora, Roboto } from "next/font/google";
import "./globals.css";

const lora = Lora({ 
  subsets: ['latin'],
  variable: '--font-lora' // <--- Este nombre debe coincidir con el de tu CSS
})

const roboto = Roboto({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${lora.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
